import G7ActualClockUnrankedRelabelling

#print axioms GProgram.G7.CompletedUnrankedRelabelling.jump_mass
#print axioms GProgram.G7.CompletedUnrankedRelabelling.jump_choice
#print axioms GProgram.G7.CompletedUnrankedRelabelling.jump_step
#print axioms GProgram.G7.CompletedUnrankedRelabelling.ancestral_completion
#print axioms GProgram.G7.CompletedUnrankedRelabelling.completion_kernel
#print axioms GProgram.G7.CompletedUnrankedRelabelling.natural_completed
#print axioms GProgram.G7.CompletedUnrankedRelabelling.unranked_readout
#print axioms GProgram.G7.CompletedUnrankedRelabelling.natural_completed_unranked
#print axioms GProgram.G7.ActualClockUnrankedRelabelling.conditional_readout
#print axioms GProgram.G7.ActualClockUnrankedRelabelling.forestMeasurable
#print axioms GProgram.G7.ActualClockUnrankedRelabelling.actualClockUnrankedLaw
#print axioms GProgram.G7.ActualClockUnrankedRelabelling.actual_clock_eq_unranked
#print axioms GProgram.G7.ActualClockUnrankedRelabelling.actual_clock_unranked_relabel
