import G7ProgramRelabelling

#print axioms GProgram.G7.SourceStateRelabelling.location
#print axioms GProgram.G7.SourceStateRelabelling.location_node
#print axioms GProgram.G7.SourceStateRelabelling.location_edge
#print axioms GProgram.G7.SourceStateRelabelling.location_root
#print axioms GProgram.G7.SourceStateRelabelling.event
#print axioms GProgram.G7.SourceStateRelabelling.state
#print axioms GProgram.G7.SourceStateRelabelling.valid
#print axioms GProgram.G7.SourceStateRelabelling.copyLocation_map
#print axioms GProgram.G7.SourceStateRelabelling.descends_iff
#print axioms GProgram.G7.SourceStateRelabelling.sourceValid
#print axioms GProgram.G7.SourceStateRelabelling.initial_commutes
#print axioms GProgram.G7.SourceStateRelabelling.merge_commutes
#print axioms GProgram.G7.SourceStateRelabelling.legalMerge_iff
#print axioms GProgram.G7.SourceStateRelabelling.transport_commutes
#print axioms GProgram.G7.SourceStateRelabelling.location_eq_node
#print axioms GProgram.G7.SourceStateRelabelling.location_eq_edge
#print axioms GProgram.G7.SourceStateRelabelling.exitEdge_commutes
#print axioms GProgram.G7.SourceStateRelabelling.enterEdge_commutes
#print axioms GProgram.G7.SourceStateRelabelling.enterRoot_commutes
#print axioms GProgram.G7.SourceStateRelabelling.atNodeEquiv
#print axioms GProgram.G7.SourceStateRelabelling.pulse_commutes
#print axioms GProgram.G7.SourceStateRelabelling.commonPulse_commutes
#print axioms GProgram.G7.SnapshotRelabelling.snapshot
#print axioms GProgram.G7.SnapshotRelabelling.decode_commutes
#print axioms GProgram.G7.SnapshotRelabelling.encode_commutes
#print axioms GProgram.G7.SnapshotRelabelling.snapshot_valid
#print axioms GProgram.G7.SnapshotRelabelling.code
#print axioms GProgram.G7.SnapshotRelabelling.code_state
#print axioms GProgram.G7.SnapshotRelabelling.admittedCode_commutes
#print axioms GProgram.G7.SnapshotRelabelling.entire_genealogy_preserved
#print axioms GProgram.G7.CoinReindexing.coinTransport
#print axioms GProgram.G7.CoinReindexing.current_coin_measure
#print axioms GProgram.G7.CoinReindexing.current_coin_pmf
#print axioms GProgram.G7.CoinReindexing.original_gamma_preserved
#print axioms GProgram.G7.CoinReindexing.original_coin_measure
#print axioms GProgram.G7.BoundaryRelabelling.admitted_congr
#print axioms GProgram.G7.BoundaryRelabelling.pulse_state_congr
#print axioms GProgram.G7.BoundaryRelabelling.operation
#print axioms GProgram.G7.BoundaryRelabelling.exit_code
#print axioms GProgram.G7.BoundaryRelabelling.ordinary_code
#print axioms GProgram.G7.BoundaryRelabelling.root_code
#print axioms GProgram.G7.BoundaryRelabelling.owners
#print axioms GProgram.G7.BoundaryRelabelling.pulse_code
#print axioms GProgram.G7.BoundaryRelabelling.independent_kernel
#print axioms GProgram.G7.BoundaryRelabelling.boundary_kernel
#print axioms GProgram.G7.SourceStepRelabelling.pair_rate
#print axioms GProgram.G7.SourceStepRelabelling.place
#print axioms GProgram.G7.SourceStepRelabelling.roots
#print axioms GProgram.G7.SourceStepRelabelling.choices
#print axioms GProgram.G7.SourceStepRelabelling.choice_place
#print axioms GProgram.G7.SourceStepRelabelling.choice_pair
#print axioms GProgram.G7.SourceStepRelabelling.choice_rate
#print axioms GProgram.G7.SourceStepRelabelling.total_rate
#print axioms GProgram.G7.SourceStepRelabelling.global_rate
#print axioms GProgram.G7.SourceStepRelabelling.choice_mass
#print axioms GProgram.G7.SourceStepRelabelling.pmf_map_equiv_apply
#print axioms GProgram.G7.SourceStepRelabelling.choice_pmf
#print axioms GProgram.G7.SourceStepRelabelling.destination
#print axioms GProgram.G7.SourceStepRelabelling.source_step
#print axioms GProgram.G7.ProgramRelabelling.iteration
#print axioms GProgram.G7.ProgramRelabelling.global_clock
#print axioms GProgram.G7.ProgramRelabelling.time_kernel
#print axioms GProgram.G7.ProgramRelabelling.programStep
#print axioms GProgram.G7.ProgramRelabelling.program_step
#print axioms GProgram.G7.ProgramRelabelling.program
