import G7OriginalAdmission

#print axioms GProgram.G7.sum_inDegree
#print axioms GProgram.G7.sum_outDegree
#print axioms GProgram.G7.hybridCount
#print axioms GProgram.G7.leafSet
#print axioms GProgram.G7.leafSet_card
#print axioms GProgram.G7.degree_local_in
#print axioms GProgram.G7.degree_local_out
#print axioms GProgram.G7.original_census
#print axioms GProgram.G7.OriginalRelabelling.graph
#print axioms GProgram.G7.OriginalRelabelling.graph_source
#print axioms GProgram.G7.OriginalRelabelling.graph_target
#print axioms GProgram.G7.OriginalRelabelling.dstep_iff
#print axioms GProgram.G7.OriginalRelabelling.dreach_iff
#print axioms GProgram.G7.OriginalRelabelling.acyclic
#print axioms GProgram.G7.OriginalRelabelling.avoidReach_iff
#print axioms GProgram.G7.OriginalRelabelling.dominates_iff
#print axioms GProgram.G7.OriginalRelabelling.inDegree_eq
#print axioms GProgram.G7.OriginalRelabelling.outDegree_eq
#print axioms GProgram.G7.OriginalRelabelling.hybrid_iff
#print axioms GProgram.G7.OriginalRelabelling.network
#print axioms GProgram.G7.OriginalRelabelling.calendar
#print axioms GProgram.G7.OriginalRelabelling.rates
#print axioms GProgram.G7.OriginalRelabelling.hybrids
#print axioms GProgram.G7.OriginalRelabelling.inheritance
#print axioms GProgram.G7.OriginalRelabelling.calendar_duration_preserved
#print axioms GProgram.G7.OriginalRelabelling.hazard_preserved
#print axioms GProgram.G7.OriginalRelabelling.parents
#print axioms GProgram.G7.OriginalRelabelling.registry
#print axioms GProgram.G7.OriginalRelabelling.parent_bit_preserved
#print axioms GProgram.G7.OriginalRelabelling.inheritance_preserved
#print axioms GProgram.G7.OriginalRelabelling.inc_iff
#print axioms GProgram.G7.OriginalRelabelling.ustep_iff
#print axioms GProgram.G7.OriginalRelabelling.ureach_iff
#print axioms GProgram.G7.OriginalRelabelling.bridge_iff
#print axioms GProgram.G7.OriginalRelabelling.cut_child_preserved
#print axioms GProgram.G7.OriginalFiniteEncoding.vertexCount
#print axioms GProgram.G7.OriginalFiniteEncoding.edgeCount
#print axioms GProgram.G7.OriginalFiniteEncoding.hybrid_card
#print axioms GProgram.G7.OriginalFiniteEncoding.original_registry_sizes
#print axioms GProgram.G7.OriginalFiniteEncoding.vertexNumbering
#print axioms GProgram.G7.OriginalFiniteEncoding.edgeNumbering
#print axioms GProgram.G7.OriginalFiniteEncoding.Code
#print axioms GProgram.G7.OriginalFiniteEncoding.allCodes
#print axioms GProgram.G7.OriginalFiniteEncoding.encode
#print axioms GProgram.G7.OriginalFiniteEncoding.every_original_source_has_code
#print axioms GProgram.G7.OriginalFiniteEncoding.numberedSource
#print axioms GProgram.G7.OriginalFiniteEncoding.encoded_graph_exact
#print axioms GProgram.G7.OriginalFiniteEncoding.encoded_parent_target
#print axioms GProgram.G7.OriginalFiniteEncoding.encoded_parent_bits_distinct
#print axioms GProgram.G7.FiniteReachability.grow
#print axioms GProgram.G7.FiniteReachability.reached
#print axioms GProgram.G7.FiniteReachability.subset_grow
#print axioms GProgram.G7.FiniteReachability.grow_mono
#print axioms GProgram.G7.FiniteReachability.reached_step
#print axioms GProgram.G7.FiniteReachability.reached_mono
#print axioms GProgram.G7.FiniteReachability.self_mem
#print axioms GProgram.G7.FiniteReachability.reached_sound
#print axioms GProgram.G7.FiniteReachability.stable_later
#print axioms GProgram.G7.FiniteReachability.exists_stable
#print axioms GProgram.G7.FiniteReachability.reached_complete
#print axioms GProgram.G7.FiniteReachability.reached_iff
#print axioms GProgram.G7.FiniteReachability.decideReach
#print axioms GProgram.G7.OriginalAdmission.decidableDStep
#print axioms GProgram.G7.OriginalAdmission.decidableDReach
#print axioms GProgram.G7.OriginalAdmission.decidableTransGen
#print axioms GProgram.G7.OriginalAdmission.decidableAcyclic
#print axioms GProgram.G7.OriginalAdmission.decidableAvoidReach
#print axioms GProgram.G7.OriginalAdmission.decidableDominates
#print axioms GProgram.G7.OriginalAdmission.decidableInc
#print axioms GProgram.G7.OriginalAdmission.decidableUStep
#print axioms GProgram.G7.OriginalAdmission.decidableUReach
#print axioms GProgram.G7.OriginalAdmission.decidableBridge
#print axioms GProgram.G7.OriginalAdmission.decidableHybrid
#print axioms GProgram.G7.OriginalAdmission.NV
#print axioms GProgram.G7.OriginalAdmission.NE
#print axioms GProgram.G7.OriginalAdmission.codeGraph
#print axioms GProgram.G7.OriginalAdmission.codeRoot
#print axioms GProgram.G7.OriginalAdmission.codeLeaf
#print axioms GProgram.G7.OriginalAdmission.BinaryValid
#print axioms GProgram.G7.OriginalAdmission.decidableBinaryValid
#print axioms GProgram.G7.OriginalAdmission.CutChild
#print axioms GProgram.G7.OriginalAdmission.decidableCutChild
#print axioms GProgram.G7.OriginalAdmission.sourceOfValid
#print axioms GProgram.G7.OriginalAdmission.binaryCutChildCodes
#print axioms GProgram.G7.OriginalAdmission.encoded_binary_valid
#print axioms GProgram.G7.OriginalAdmission.encoded_cut_child
#print axioms GProgram.G7.OriginalAdmission.codeSite
#print axioms GProgram.G7.OriginalAdmission.codeParent
#print axioms GProgram.G7.OriginalAdmission.RegistryValid
#print axioms GProgram.G7.OriginalAdmission.decidableRegistryValid
#print axioms GProgram.G7.OriginalAdmission.registeredBinaryCutChildCodes
#print axioms GProgram.G7.OriginalAdmission.encoded_registry_valid
#print axioms GProgram.G7.OriginalAdmission.every_registered_source_survives_filter
#print axioms GProgram.G7.OriginalAdmission.decodedHybridMap
#print axioms GProgram.G7.OriginalAdmission.decodedHybridMap_bijective
#print axioms GProgram.G7.OriginalAdmission.decodedIDs
#print axioms GProgram.G7.OriginalAdmission.decodedRegistry
#print axioms GProgram.G7.OriginalAdmission.decoded_parent_exact
