"""Read-only conditional component selection, distinct from full181 repair."""
from pathlib import Path
import json,hashlib,re,shutil
root=Path('/workspace/cloud-lean');packet='research/2026-10-07-cloud-g6-sol-ultra-1601z';prep=root/packet/'verification/preparation/minimal-generic-component-0757z';prep.mkdir(parents=True,exist_ok=True)
option=json.load(open('/tmp/g6-minimal-closure-options-actual179.json'))['generic-closure-attainment'];source_context=json.load(open('/tmp/g6-three-followon-external-context-authenticated.json'));prior=root/packet/'verification/evidence/g6-run-37738512508-PASS';inputs=json.loads((prior/'inputs-recovered.json').read_text());records=option['modules'];hashb=lambda b:hashlib.sha256(b).hexdigest();new=[m for m in option['order'] if m not in inputs['modules']]
for m in new:
 r=records[m];data=Path(r['path']).read_bytes();assert hashb(data)==r['sha256'];p=prep/'sources'/(m.replace('.','/')+'.lean');p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data)
# The observed failed finite boundary must never be silently reenrolled.
f='UnifiedLean.G6.FiniteCorruptionBoundary';candidate=Path('/workspace/FiniteCorruptionBoundary-sum-div-direction-repair.lean').read_bytes();assert hashb(candidate)=='6b5964de36b9cc4f2e79d4d7e8652498b8f2517e98769c1b9aa6938bf197754a';original=(prep/'sources/UnifiedLean/G6/FiniteCorruptionBoundary.lean');original.rename(original.with_name('FiniteCorruptionBoundary-failed-original.lean'));(prep/'sources/UnifiedLean/G6/FiniteCorruptionBoundary.lean').write_bytes(candidate)
records[f]={**records[f],'sha256':hashb(candidate),'git_blob_sha':hashlib.sha1(b'blob '+str(len(candidate)).encode()+b'\0'+candidate).hexdigest(),'bytes':len(candidate),'identity':'Root6b5964 proof-direction candidate; compiler UNCHECKED until same181 repair disposition; no prospective acceptance','candidate_author_commit':'263ba2e3c970ed8a16ff3f73c5298598927412da','candidate_copy':str((prep/'sources/UnifiedLean/G6/FiniteCorruptionBoundary.lean').relative_to(root))}
for m in set(records)&set(inputs['modules']):assert records[m]['sha256']==inputs['modules'][m]['sha256']
plan={'status':'CONDITIONAL PREPARATION ONLY; original181 repair disposition MUST close first; no freeze/launch','separate_component_scope':'Generic finite PMF class closure, coordinate-simplex compact closest law, coordinate/TV closure equivalence and radial expanded closure; native original wrong-source image/target consumers excluded','rooted_targets':option['targets'],'targets':option['targets'],'custom_modules':69,'prior_actual179_source_count':64,'new_vs_actual179':5,'new_module_names':new,'modules':records,'topological_order':option['order'],'mathlib_roots':[m for m in option['external_roots'] if m.startswith('Mathlib.')],'lean_roots':[m for m in option['external_roots'] if m.startswith('Lean.')],'named_declarations_by_target':option['named_declarations_by_target'],'named_total':43,'literal_print_directive_total':35,'complete_inventory':'Complete all69 successful owned declarations including generated/type/body references/transitive axioms; no prospective count supplied','preservation':'All current179/181 sources/workflows/runtime/caps stay immutable. A later component would select ONLY its exact original dependency closure, not replay unrelated179 roots; prior disjoint inventories remain evidence with no summed union claim','source_binding_gates':'Current6b5964 failed-provider repair is pending compilation;4other originals have prior source/API gates but are compiler UNCHECKED. Fresh independent exact component selection/root scope/budget/ONE launch authorization required; no current gate covers it','prior_actual179_acceptance':'7126a5d4386652abbcfb224f075d0dcfac716797','prior_failed181_owner_receipt':'6a1966832b799620223e2ba7c4ecd908c074d1a8','source_graph':option['external_context_against_actual179'],'cache_scope':'Prior actual179 downloaded/decompressed3584 cache file objects. This candidate has only a derived3582 source-package-header closure, NOT a cache execution or object count. Source-header nodes3318Mathlib+264other; no added source node against old3320+264 header manifest. Actual historical3302 cache figure is a separate dated stage','controls':'unchanged900job/180command/--trust=0/-j1/-M4096; exactrunner+AuditTemplate as current181','timing':option['budget_seconds'],'budget_requires_update':'Use actual tested finite boundary receipt/current repair gate if eventually accepted; final baseline/timing/external fresh pins/source scope must be independently reviewed before any selection','compiler_invocations':0,'launch_authorized':False}
(prep/'CONDITIONAL-SELECTION.json').write_text(json.dumps(plan,indent=2)+'\n');(prep/'ACTUAL179-COMMAND-TIMINGS.json').write_text(json.dumps(option['actual179_command_timings'],indent=2)+'\n');(prep/'REQUESTED-TARGETS.txt').write_text('\n'.join(option['targets'])+'\n')
# Record the exact source-header algorithm input and successful path/time mapping.
(prep/'EXTERNAL-CONTEXT-SCOPE.json').write_text(json.dumps({'header_manifest_repository_path':packet+'/verification/preparation/three-reviewed-followon-actual176-0503z/EXTERNAL-SOURCE-CONTEXT.json','header_manifest_sha256':'3e32054db98ed0a3344258fafeba07630e121cd21bb386649e49fe0abe64cce8','header_parser_scope':source_context['parser_scope'],'old3320Mathlib3584sourcepackages':True,'candidate_header_scope':option['external_context_against_actual179'],'actual179_cache_object_count':3584,'cache_correction_commit':'a77c9cee09f0b36c9c8eb86bb58fb1fae3b80f82','newMathlib_root_names_already_in_actual179_source_context':option['new_external_roots_vs179'],'source_cache_execution_distinct':True},indent=2)+'\n')
shutil.copyfile(__file__,prep/'prepare-static-component.py')
(prep/'README.md').write_text('''# Conditional69-module generic closure component\n\nPreparation only, not enrolled or compiled. The current same181 finite-corruption repair and its actual terminal/evidence disposition take priority. This candidate component retains every original import and all64 actually accepted provider hashes it needs, plus5new module sources. Root's6b5964 direction candidate replaces the known failed finite-boundary original explicitly; it is not accepted by this plan. The failed original is preserved separately.\n\nFour roots select43def/lemma/theorem names versus35literal print directives. The complete69-module generated/type/body/transitive-axiom inventory would be a third actual verification result. Generic corruption classes, compact coordinate closest laws, coordinate/TV closure equivalence and radial expansions are the mathematical scope. Actual wrong-source graph images, paired/native menus and closest laws for those native images are absent and remain unverified. This is not a full179/181 replay or a summed inventory union.\n\nExact prior64 command times total208.030015s by logical-module→actual staged-path mapping. A proposed conservative estimate is561.814686s: that208.030015 +93.784671(full prior179 noncustom job overhead) +150(30s per5new module) +10additionalaudit +100variation, under unchanged900/180caps. This is not a guarantee or launch gate; it must be revised against actual successful finite-boundary timing and fresh independent/root source-selection checks.\n\nDerived external header closure is3318Mathlib source nodes+264other=3582source-package pins, a strict subset of the separately pinned older3320+264=3584 source-header graph. Three new root NAMES were already in that graph. Actual179 cache download/decompression was3584cache file objects, distinct from source files; no prospective cache execution/count is inferred. Historical3302 belongs to an earlier stage and is corrected additively.\n\nCurrent sources/targets/providers/workflow/runtime/AuditTemplate/caps remain fixed. No compiler, cache, Actions watch/dispatch or numerical solver was run in this preparation. Final physical applicability, effective source nets and fullG6 master remain separate.\n''')
# Pin actual staged paths and distinguish the new failed-provider derivative.
final=json.loads((prep/'CONDITIONAL-SELECTION.json').read_text())
for module in final['new_module_names']:
    record=final['modules'][module]
    staged=prep/'sources'/(module.replace('.','/')+'.lean')
    assert hashb(staged.read_bytes())==record['sha256']
    record['path']=str(staged)
    record['staged_source_path']=str(staged.relative_to(root))
    record['eventual_formal_repository_path']=packet+'/sources/'+module.replace('.','/')+'.lean'
    if module=='UnifiedLean.G6.FiniteCorruptionBoundary':
        record['original_failed_repository_path']=record['repository_path']
        record['repository_path']=packet+'/sources/UnifiedLean/G6/FiniteCorruptionBoundary.lean'
        record['expected_sha256']=record['sha256']
        record['current_frozen_source']='916e02a1d51d79cdffd300b9d8313df2608b08bc'
        record['identity']='Root6b5964 currently frozen in sole181run37749239915; compilerUNCH until terminal'
final['current_authorized_input']='916e02a1d51d79cdffd300b9d8313df2608b08bc'
final['current_sole_run']=37749239915
final['current_run_is_immutable_and_not_modified']=True
(prep/'CONDITIONAL-SELECTION.json').write_text(json.dumps(final,indent=2)+'\n')
shutil.copyfile(__file__,prep/'prepare-static-component.py')
print(json.dumps({'prepared':str(prep),'modules':69,'prior_sources_fixed':64,'new_sources':5,'roots':4,'selected':43,'budget_estimate':plan['timing']['sum'],'launch_authorized':False},indent=2))
