import G7NaturalCalendarRelabelling

#print axioms GProgram.G7.NaturalWordRelabelling.register_commutes
#print axioms GProgram.G7.NaturalWordRelabelling.original_coin_pmf
#print axioms GProgram.G7.NaturalWordRelabelling.register_pmf
#print axioms GProgram.G7.NaturalWordRelabelling.initial_code
#print axioms GProgram.G7.NaturalWordRelabelling.initialized_word
#print axioms GProgram.G7.GlobalOwnerCoins.restrictOwners
#print axioms GProgram.G7.GlobalOwnerCoins.restricted_pmf
#print axioms GProgram.G7.GlobalOwnerCoins.independent_pulse_fixed_carrier
#print axioms GProgram.G7.BoundaryExitCommutation.exit_location_commute
#print axioms GProgram.G7.BoundaryExitCommutation.exit_code_commute
#print axioms GProgram.G7.NodeActions.Action
#print axioms GProgram.G7.NodeActions.site
#print axioms GProgram.G7.NodeActions.operation
#print axioms GProgram.G7.NodeActions.coinLaw
#print axioms GProgram.G7.NodeActions.destination
#print axioms GProgram.G7.NodeActions.target
#print axioms GProgram.G7.NodeActions.route
#print axioms GProgram.G7.NodeActions.target_not_node
#print axioms GProgram.G7.NodeActions.route_commute
#print axioms GProgram.G7.NodeActions.kernel_fixed_carrier
#print axioms GProgram.G7.NodeActions.destination_live
#print axioms GProgram.G7.NodeActions.destination_ancestor
#print axioms GProgram.G7.NodeActions.destination_register
#print axioms GProgram.G7.NodeActions.destination_genealogy
#print axioms GProgram.G7.NodeActions.destination_location
#print axioms GProgram.G7.NodeActions.Canonical
#print axioms GProgram.G7.NodeActions.admitted_canonical
#print axioms GProgram.G7.NodeActions.canonical_ext
#print axioms GProgram.G7.NodeActions.destination_canonical
#print axioms GProgram.G7.NodeActions.state_ext
#print axioms GProgram.G7.NodeActions.destination_commute
#print axioms GProgram.G7.NodeActions.kernels_commute
#print axioms GProgram.G7.NodeActions.originalAction
#print axioms GProgram.G7.NodeActions.original_operation
#print axioms GProgram.G7.NodeActions.original_site
#print axioms GProgram.G7.BoundaryPhasePermutation.program_append
#print axioms GProgram.G7.BoundaryPhasePermutation.boundary_perm
#print axioms GProgram.G7.BoundaryPhasePermutation.exit_phase_perm
#print axioms GProgram.G7.BoundaryPhasePermutation.node_phase_perm
#print axioms GProgram.G7.CalendarNodeRelabelling.incoming_unique
#print axioms GProgram.G7.CalendarNodeRelabelling.ordinary_selector
#print axioms GProgram.G7.CalendarNodeRelabelling.gamma
#print axioms GProgram.G7.CalendarNodeRelabelling.common
#print axioms GProgram.G7.CalendarNodeRelabelling.node_operation
#print axioms GProgram.G7.CalendarAgendaRelabelling.filtered_registry_perm
#print axioms GProgram.G7.CalendarAgendaRelabelling.dates
#print axioms GProgram.G7.CalendarAgendaRelabelling.sorted_dates
#print axioms GProgram.G7.CalendarAgendaRelabelling.exit_registry_perm
#print axioms GProgram.G7.CalendarAgendaRelabelling.node_registry_perm
#print axioms GProgram.G7.CalendarAgendaRelabelling.boundary_agenda
#print axioms GProgram.G7.NaturalCalendarRelabelling.tail_agenda
#print axioms GProgram.G7.NaturalCalendarRelabelling.compiled_agenda
#print axioms GProgram.G7.NaturalCalendarRelabelling.conditional_calendar
#print axioms GProgram.G7.NaturalCalendarRelabelling.natural_calendar
