import Lake
open Lake DSL
package unifiedLean where
  moreLeanArgs := #["-j1", "-M4096"]
require mathlib from "deps/mathlib"
lean_lib ImportedProofs where
  srcDir := "Imported"
  roots := #[`E8CertificateStability, `E8DeterministicTopKCertificate, `E8ExactResidualMass, `E8FiniteTracebackLaw, `E8GridTracebackBridge, `E8MidpointGridLaw, `E8MidpointGridTV, `E8MidpointProductionKernel, `E8ObservablePrefixLaw, `E8SCFG2ProviderBoundaryContract, `E8SCFG2RuntimeChildAdapter, `E8SamplerBridgeAudit, `E8ScheduledDerivationSum, `E8ScheduledHypergraphCorrectness, `E8ScheduledObserverFrame, `E8SelectedMassInclusionExclusion, `E8SourceVBranchBound, `E8StrictPrefixSelector, `E8SupportedTracebackLaw, `E8TracebackCallRanks, `E8TracebackErrorComposition, `E8UniformPrefixLaw, `ExponentialClockMoments, `G1SharedRegisterStress, `G2LiveLineageRouting, `G3AllResidueNormalIdentities, `G3AllResiduePositivity, `G3BernoulliCriticalNumerators, `G3BernoulliDerivatives, `G3BernoulliVerticalExclusion, `G3CapSixDeterminant, `G3FiniteMomentBarrier, `G3FixedDegreeResultants, `G4AllRootBinomialCompression, `G4AllRootPairClocks, `G4BalancedForestIdentity, `G4FourRootPositivity, `G4IndependentRoutingBridge, `G4KingmanHankelObstruction, `G4OrdinaryTripletReadout, `G4PathResolvedMeasurement, `G4TwoRootSourceStopping, `G5ActualComponentSupport, `G5BoundedExactBlock, `G5BridgeBarrier, `G5BridgeComponentEntries, `G5CalendarRoutes, `G5ComponentCalendarCoverage, `G5CoupledGroupSemantics, `G5CoupledQuartetKernel, `G5CurrentPortTwoPositions, `G5CutChildNecessity, `G5ExponentialGermIdentification, `G5FairMomentQuartetTransport, `G5FairOriginalCoinLaw, `G5FairSelectorMoments, `G5FourGroupCriterion, `G5FourGroupSupportCases, `G5GroupRelabeling, `G5MinimalGraphInterface, `G5NonbridgeRouteBound, `G5OneIntersectionCase, `G5OriginalCoinPMF, `G5OriginalRouteHazard, `G5OriginalTipCurrentSupport, `G5PairMomentCases, `G5PairOnlySureBlockChronology, `G5ParentChoiceCalendar, `G5ParentPositionPushforward, `G5ProtectiveBlock, `G5RootRouteCurrentSupport, `G5SafePastHybridDisjointness, `G5SafePastMeetingPermanence, `G5ThreeGroupKernel, `G5TwoIntersectionCase, `G5UnknownRateSupport, `G6BridgeCannotEnterHybrid, `G7OriginalCensus, `GraphBlobs, `GraphCuts, `GraphLeaves, `GraphSwitching, `KingmanFiniteChernoff, `KingmanFiniteClockTail, `RawSourceAnchorLocalization, `RepresentationTransport, `SourceForestKingmanPopulationProjection, `SourceForestKingmanProjection, `SourceLabelledForest, `SourceNetwork, `VerifiedAlgebraComponents, `VerifiedAllRootComponents, `VerifiedBridgeEntry, `VerifiedClockTailComponents, `VerifiedComponents, `VerifiedFullComponentCheckpoint, `VerifiedLeanFirstCheckpoint, `VerifiedRoutingBridge]
lean_lib HistoricalCore where
  srcDir := "HistoricalCore"
  roots := #[`SamuelAlexanderResearch]
lean_lib HistoricalNanuq where
  srcDir := "HistoricalNanuq"
  roots := #[`AllLevelParameterDomain, `AnchorAdjacency, `AnchorCanonicalOrder, `AnchorComposition, `AnchorCompression, `AnchorCompressionOrder, `AnchorIndexTransport, `AnchorLeafPosition, `AnchorMetricOrder, `AnchorNondegenerate, `AnchorPortCounts, `AnchorPortFibers, `AnchorPortPatterns, `AnchorPortValues, `AnchorThetaBridge, `CircularBasis, `CircularBoundary, `CircularComposition, `CircularDecomposition, `CircularMixture, `CircularRestriction, `CircularSupportCompression, `CircularThetaCuts, `CircularThetaSupport, `GraphBlobLeaves, `GraphBlobMedian, `GraphBlobOrientation, `GraphBlobPorts, `GraphBridgeSplits, `GraphGalls, `GraphMedianUnique, `GraphPortConsequences, `GraphPortFibers, `GraphPortTransport, `GraphPorts, `GraphQuartetBridge, `GraphQuartetExistence, `GraphSwitchingChoices, `GraphSwitchingCuts, `GraphSwitchingDegree, `GraphSwitchingExistence, `GraphSwitchingFinite, `GraphTreePorts, `IntervalBoundary, `QuartetComposition, `QuartetCompositionDependent, `QuartetSemantics, `RawNanuq, `SourceBlobFacts, `SourceCompositionBridge, `SourceFacts, `SourceQuartetRelation, `SourceQuartetSymmetry, `SourceResolve, `SplitReconstruction, `ThetaArmMetric, `ThetaArmOrder, `ThetaBumpedMetric, `ThetaCertificate1, `ThetaCertificate2, `ThetaCertificate3, `ThetaCertificate4, `ThetaCompressedSurjective, `ThetaCompression, `ThetaDisplayedSemantics, `ThetaEdgeQuartet, `ThetaFinite, `ThetaFiniteSoundness, `ThetaPathLengths, `ThetaPathMembership, `ThetaQuartetEdge, `ThetaQuartetOrder, `ThetaQuartetSymmetry, `ThetaQuartetValidity, `ThetaSemanticsBridge, `ThetaSourceExact, `ThetaSupport, `ThetaSupportCertificate1, `ThetaSupportCertificate2, `ThetaSwitchingEdges, `ThetaWitnessSymmetry, `TreePathCounting, `TwoSwitchings, `WeightedAnchor, `WeightedCoefficients, `WeightedOrderedPairs, `WeightedProperties, `WeightedRestriction, `WeightedSmallPorts, `WeightedSource]
-- Matches the original historical PASS resource bound for this concrete certificate.
lean_lib HistoricalThetaFive where
  srcDir := "HistoricalNanuq"
  roots := #[`ThetaCertificate5]
  moreLeanArgs := #["-M6144"]
lean_lib HistoricalBiological where
  srcDir := "HistoricalBiological"
  roots := #[`PairingBridge, `PairingCore, `PairingGARG, `PairingObservation, `PairingObservationAudit, `PedigreeBlockAudit, `PedigreeBlockDependence, `PedigreeBlockGraph, `PedigreeBlockModel, `PedigreeBlockObservation, `PedigreeBlockProbability, `PedigreeBlockRecovery, `RealBridges, `WongAlexander, `WongGARG]
@[default_target]
lean_lib UnifiedLean
