from pathlib import Path
import sys,json,subprocess,hashlib
repo=Path('/workspace/cloud-lean');run_id=sys.argv[1];result=sys.argv[2];packet=repo/'research/2026-10-07-cloud-g6-sol-ultra-1601z';evidence=packet/'verification/evidence'/('g6-run-'+run_id+'-'+result)
inputs=json.loads((evidence/'inputs-recovered.json').read_text());commands=json.loads((evidence/'receipts-recovered.json').read_text());audit=json.loads((evidence/'axiom-audit-recovered.json').read_text());complete=json.loads((evidence/'complete-ownership-receipt.json').read_text());jobs=json.loads((evidence/'jobs.json').read_text())['jobs'];job=jobs[0];rows=json.loads((evidence/'complete-environment-inventory.json').read_text())['declarations'];payload=complete['payload']
snapshot=Path('/tmp/g6-frozen-'+inputs['source_commit'])
snapshot_readback=json.loads((snapshot/'source-readback.json').read_text());assert snapshot_readback['commit']==inputs['source_commit']
def frozen_bytes(path):
 data=(snapshot/path).read_bytes();assert hashlib.sha256(data).hexdigest()==snapshot_readback['files'][path],path
 return data
selection_plan_name=sys.argv[3] if len(sys.argv)>3 else 'calendar-bank-cut-static.json'
selection_plan=json.loads(frozen_bytes('research/2026-10-07-cloud-g6-sol-ultra-1601z/verification/freeze-plans/'+selection_plan_name))
g3_named_modules=['HybridSizeCore','G3ApproximateMomentBarrier','FiniteTagDecoder','LiteralSameBinTrace','CompleteCalendarBinReadout','ActualTailBinRow','CompleteCalendarJointLaw','ActualCutTagRefinement','ActualCutJointLaw','ActualCalendarCutContext','ActualFiniteCutJointLaw','ActualCalendarEndpointHistory','ActualObservationCutRefinement']
new_sections=[]
for target,title,scope in [
 ('UnifiedLean.G6.FiniteCorruptionBoundary','Sharp finite-output corruption boundary','Closed total-variation balls around two finite PMFs intersect exactly when their separation is at most twice the radius. The equal-radius midpoint and sharp disjointness boundary are proved, including equality; the approximation-margin corollary uses the stated validated TV error. No actual wrong-source image, compact native target menu or executable search is assumed.'),
 ('ActualObservationCorruption','Actual natural completed observation corruption margin','The actual naturally initialized correlated past and once-drawn register are mapped through the SAME original suffix calendar and exact completion to one finite joint readout. The accepted future-prefix approximation supplies the error premise for the finite corruption margin against a supplied PMF on that same alphabet. This does not admit that supplied alternative as a native wrong-source image or close the graph menu, source-class separation or full G6 master.'),
 ('HybridSizeCore','Scalar hybrid cell and discounted recurrence','The source proves polynomial cell identities, complete-cube lower bounds, and a finite discounted recurrence under its explicit scalar premises. It does not attach these scalar variables to an arbitrary original graph, grouped parent path or actual source law.'),
 ('NaturalPastCompleteObservation','Actual natural correlated past with exact suffix completion','The actual natural entering Code and old-bin matrix are bound to the SAME original suffix calendar and exact completion tail. Only the future finite prefix is approximated, retaining the correlated naturally initialized past and one joint finite readout. The scalar product-deficit and occurrence budget bounds hold under the explicit root, chronology, cuts and fixed-bin contract. This does not replace those admission gates with supplied desired-law fields or establish pruning, observational menus, executable tables or full master assembly.'),
 ('UnifiedLean.G6.RationalResidualCertificate','Rational residual count coefficients and actual-source cutoff certificate','Computable rational denominator, retained mass and finite residual count weights are nonnegative, finitely supported and normalized. Their real casts agree with the accepted actual-source residual coordinates and inherited least-cutoff error. This is a supplied rational-mean count certificate, not general-real access, executable state/table enumeration, Python/Rust semantics or a joint source-cell feasibility solver.'),
 ('UnifiedLean.G6.AncestralRateFree','Actual ancestral completion is rate invariant','On the original ancestral-root support, ordered merger choices occur in the root population and the actual embedded jump law is the exact uniform rational row over its live ordered pairs. Actual source-jump and sufficient-budget completion kernels are invariant under positive rate changes. The original root/support and state remain the same, including empty and terminal carriers. This does not prove a new timed-bin/calendar row or executable backend table correspondence.'),
 ('UnifiedLean.G6.RateBankCommon','Actual source rate-bank lower comparison','Explicit componentwise lower and upper bounds on every original pair rate imply the holding and ordered-merger choice comparison, actual choice PMF comparison, SAME source destination-step domination and its finite-iteration power bound. Actual holding coefficients and original Copy carrier are used. The supplied bank inequalities remain premises; no computable general-real enclosure, parameter grid, inheritance or complete numerical program consumer is proved here.'),
 ('UnifiedLean.G6.InheritanceBankCommon','Actual current-owner and once-drawn original-register bank bounds','Original Bernoulli atom bounds multiply over the ACTUAL current AtNode coin carrier at each independent pulse, with the derived uniform Copy-cardinality exponent. Separately the ALL-original-hybrid register product supplies natural initial Code and correlated register/Code domination, so COMMON retains its once-drawn register rather than redrawing it. Physical bit-bank inequalities and initialization provider are explicit. Full mixed program/history composition and executable cell tables remain separate.'),
 ('UnifiedLean.G6.UpperRateSourceCommon','Upper count mean and perturbed physical source interval common law','The ACTUAL normalized prefix count law at a and source iteration at r form the common reference. Prefix counts above K vanish; within K the upper count witness combines with the actual rate-bank power bound. Both actual sourceTimeKernel and the upper-mean residual PMF using rhat dominate the SAME common law, deriving interval and one joint finite-readout TV bounds. Actual mean upper enclosure, bank inequalities and StepBudget remain explicit premises. This closes an interval consumer only; inheritance, full serial program/history, physical calendar attachment, executable tables and menu/master assembly remain separate.'),
 ('UnifiedLean.G6.ResidualProgram','Actual-mean residual PMF, program and full endpoint history','The PMF.ofFintype constructor has exactly the proved residual real coordinates. Actual and residual program/history laws both dominate the SAME normalized finite-prefix common law at the product of residual masses. The same initial PMF and every endpoint vector are retained jointly, including a supplied correlated old-past label and one finite joint readout. Occurrence-wise scalar errors bound the product deficit. Budget premises use the SAME actual interval means and physical rate bank; this file does not prove upper-mean program transport, physical old-past attachment or executable table correspondence.'),
 ('UnifiedLean.G6.UpperMeanCommon','Upper numerical mean scalar common-count witness','Nine elementary statements and two definitions prove polynomial differences, a positive common mass using the ACTUAL normalized count law at a and the upper residual denominator at b, actual prefix-mass domination and a deficit at most b-a plus the b residual certificate. The bank is unchanged and the reference is Qa. These are scalar count witnesses, not the assembled upper-mean source program/history consumer or an enclosure oracle.'),
 ('CompleteCalendarBinReadout','Actual complete-record finite bin readout','The SAME actual calendar and completion record supplies endpoint Code and its binned matrix. Exact fold binning, joint readout measurability and calendar-map probability are derived from inherited physical record laws. Under the explicit entering ForestDecorates premise, the complete live genealogies decode their actual pair-age tags while repeated tags retain topology. Physical initialization, whole-forest pruning and observational menu equivalence require their separate consumers.'),
 ('ActualTailBinRow','Actual tail joint source row','One original strict-positive coordinate event works for every horizon, including the SAME random clockCover. Constant-tail-bin folds then become the actual initial-to-final tag update. The raw actual completion endpoint law derives the joint endpoint/tag row under ancestral-root and last-cut premises; no desired row law is assumed.'),
 ('CompleteCalendarJointLaw','Actual complete-calendar correlated joint law','The correlated calendar pushforward supplies an actual normalized Gamma PMF. Exact finite-fibre/product regrouping and the SAME actual completion tail derive equality of the full complete-record endpoint/tag pushforward to Gamma.bind of the joint completion kernel. Explicit ancestral-root support, measurable bin and tail-cut premises are retained. This does not itself identify Gamma with the finite approximate backend or close the final pruning/physical/menu/master obligations.'),
 ('ActualCutTagRefinement','Same-clock deterministic endpoint and tag cut refinement','The original active clock records concatenate across the ACTUAL retained cut residual. Finite and completed traces preserve the endpoint Code and every carried tag through that same cut, with the stated regular-clock, budget and nonnegative-duration premises. Completion uses the SAME clockCover record. These are deterministic source identities; the joint probability-law attachment is supplied separately.'),
 ('ActualCutJointLaw','Actual complete-tail cut fibre joint law','The proved full-recorded-past terminal-fibre law derives the unconditional complete endpoint/tag pushforward after inserting the ACTUAL retained-clock cut. Each marked-prefix fibre remains unnormalized and is paired with its genuine residual complete-clock law. Readout measurability and decoded/raw endpoint fibre agreement are derived; no desired output law or success conditioning is an input.'),
 ('ActualCalendarCutContext','Actual calendar context joint readout','The actual complete-record endpoint/tag readout is transported through the finite segment-joint calendar recursion and its prefix/suffix contexts. The supplied carried tags, measurable bin and stated support/tail premises remain explicit, and boundary/fibre sums remain unnormalized. Physical initialized-past binding, executable cut construction and numerical backend equality are separate obligations.'),
 ('ActualFiniteCutJointLaw','Actual finite-interval cut fibre joint law','The SAME original-clock finite interval endpoint and carried tag matrix refine across a retained cut at the stated nonnegative durations. The full recorded-past terminal fibres derive the corresponding joint finite-interval law, and the actual interval segment readout is attached to that law. The source clocks, endpoint Code, old tags and inactive padding are retained.'),
 ('ActualCalendarEndpointHistory','Actual calendar endpoint-history attachment','The actual calendar endpoint history is attached to the original finite source history while retaining the supplied old decoration and its joint carried readout. The legal finite word/cuts and stated bin/refinement conditions remain explicit. This attachment does not establish physical initialized-past binding, rational table correspondence or a sampler.'),
 ('ActualObservationCutRefinement','Joint fixed finite observation and cut law','One fixed finite joint observation is transported through the actual endpoint-history cut law under the supplied old decoration, legal finite word/cuts and deterministic refinement/bin contract. The joint observation is retained as a single readout. Executable cut construction, rational tables, sampling and observational menu equivalence remain separate obligations.'),
 ('UnifiedLean.G6.BinClock','Actual-bin clock helper','The same original current-pair clock coordinates, active record membership, inherited horizon bound, strict positivity and fixed-boundary nullity establish that all active ages lie strictly inside the fixed bin almost surely for every finite budget. This discharges the SAME clock-record fold\'s active-bin premise, carrying the supplied old tags unchanged. It does not bind the old tags to a prior physical history or assemble the complete calendar/menu law.'),
 ('LiteralSameBinTrace','Actual literal-prefix endpoint fold','Legal-merger pair relations persist through every original finite literal clock prefix. Constant-bin folds ignore inherited age shifts and inactive padding, and their complete value equals the tag update from the actual initial to final Code. The actual-current-clock bin corollary holds almost surely for every budget and carried old tag matrix. No success/completion flag or fabricated split/rejoin record is a premise. The endpoint retains its full genealogy; actual old-decoration and whole-calendar/menu source-law assembly remain separate.'),
 ('UnifiedLean.G6.MeanEnclosure','Numerical mean enclosure through the same source','Ten proof statements and one definition prove count-coordinate exp(a-b) domination, SAME source-iteration bind domination and finite-output TV bounds by b-a plus the certified prefix deficit. Both normalized and real residual mixtures use the unchanged original physical bank and one SAME joint readout. The upper numerical mean b changes count weights only. A computable enclosure is a supplied premise; no arbitrary-real enclosure oracle, physical rate perturbation, executable correspondence or complete calendar/menu binding is claimed.'),
 ('UnifiedLean.G6.ResidualPrefix','Residual source probability vector','Nine proof statements and four definitions certify the distinct residual-lumped REAL probability vector: nonnegativity and total mass one; count coefficients taylorTerm/(S+2 next) up to K with the residual at zero; and actual-source/same-joint-readout TV bounded by 2 next/(S+2 next). The SAME finite source prefix and sourceIteration at count zero are used. This is distinct from normalized count conditioning. No executable, PMF-constructor or backend table equality is claimed; physical prior-history/calendar/tree/menu source-law assembly remains separate.'),
 ('FiniteTagDecoder','Finite-tag decoder','The inherited actual pair-age inverse on a supplied well-labelled binary genealogy commutes with binning. Repeated tags retain the binary graft topology. The fixed-tree finite-decoration instance and generated inductive declarations enter the complete ownership inventory. Unordered transport is through actual age-decorated child swaps; arbitrary symmetric matrix transport under nested swaps is not claimed. Actual source-history attachment, pruning, measurability and whole-forest law assembly remain separate.')]:
 if target not in inputs['modules']:continue
 accepted=target in audit['module_counts'];source=inputs['modules'][target]['sha256'];owned_count=complete['all_owned_counts_by_module'].get(target,0)
 if accepted:new_sections.append(f'**{title} PASS:** {audit["module_counts"][target]} named declarations and {owned_count} complete owned rows, exact source SHA256 `{source}`. {scope}')
 else:
  attempted=any(cmd['argv'][-1].endswith('/'+target.rsplit('.',1)[-1]+'.lean') for cmd in commands)
  reason='Actual compiler failure/recovery reports are rejected.' if attempted else 'A failed dependency blocked this target; its source was not compiled.'
  new_sections.append(f'**{title} not accepted:** source SHA256 `{source}`. {reason} This target has no successful named or complete ownership acceptance.')
text=f'''# Actual selected source and complete ownership result

Run [{run_id}](https://github.com/Sodelin/Research-Commons/actions/runs/{run_id}), frozen input `{inputs['source_commit']}`, job {job['id']}, {job['started_at']}–{job['completed_at']}: **{result}**. The requested closure contains {len(inputs['modules'])} custom sources and {len(inputs['mathlib_roots'])} external Mathlib roots plus one Lean root. Of {len(commands)} actual command receipts, {sum(c['exit']==0 for c in commands)} exited zero. Exact toolchain/dependency pins and unchanged baseline Lake registrations are recorded in the input manifest.

The approved `{selection_plan_name}` selection requests {selection_plan['custom_modules']} custom sources and {selection_plan['named_total']} named declarations: {selection_plan['namespace_counts']['G6']} G6, {selection_plan['namespace_counts']['G3']} G3 and {selection_plan['namespace_counts']['G5']} G5. These are requested plan counts; actual successful audits below determine acceptance.

The selected named audit has **{len(audit['named_declarations'])} exact declaration reports**, with no missing or additional reports and only standard foundational axioms. It contains {sum(count for module,count in audit['module_counts'].items() if module.startswith('UnifiedLean.G6.') or module in {'PrivateSeedFactorization','PrivateSeedHistoryFactorization','NaturalCalendarPastAdmission','NaturalPastCompleteObservation','ActualObservationCorruption'})} G6, {sum(count for module,count in audit['module_counts'].items() if module in g3_named_modules)} G3 and {audit['module_counts'].get('G5FrozenTripleAnalyticSupport',0)} G5 declarations. Named audit stdout SHA256 is `{audit['named_stdout_sha256']}`.

The distinct **complete custom environment inventory** enumerates {payload['declaration_count']} owned declarations, including {payload['theorem_declaration_count']} theorems, across {payload['selected_custom_modules']} actual successful custom modules. Generated definitions, instances, inductive types, constructors and recursors are included. Every row contains its Lean-reported type and opaque-enabled body constant references and complete transitive axiom set. Owned axioms, nonstandard rows and missing selected modules are all zero. This audit uses the attributed original dot AuditTemplate, with exact template/helper hashes recorded in the runtime dependency manifest.

The complete raw inventory is recovered losslessly from the actual terminal gzip/base64 payload: {payload['bytes']} bytes, SHA256 `{payload['sha256']}`. Its reconstructed audit source SHA256 is `{payload['audit_source_sha256']}`, and actual audit stdout SHA256 is `{complete['complete_audit_stdout_sha256']}`. All {len(inputs['modules'])} requested source hashes match exact frozen Git blobs. Every custom/final-audit stdout recovered by this receipt matches its actual command hash; cache progress rendering is excluded from stdout reconstruction.

'''+ '\n\n'.join(new_sections)+'''

All earlier accepted G6 helper sources retain their hashes and precise scopes: finite source endpoint-vector conditioning, serial TV/error budgets, rational mean least-cutoff search, pointwise actual pair update coarsening and same-record age fold. The original `Code` snapshot still erases event history. Correlated past labels are preserved from a supplied same initial PMF; attachment to the actual physical old-past law is a separate theorem. The rational count certificate does not prove general-real parameter enclosures or equivalence with the old residual-lumped table backend.

This is a fresh selected custom closure and complete owned-declaration/reference inventory for this exact input. Imported Mathlib objects are cache reuse. It is not a fresh complete 825-source corpus build and does not close G5/G6 master obligations. Prior stopped and failed run evidence remains unchanged.

`actions.log`, run/job metadata, all command times/exits/hashes, every requested source hash, selected target stdout, both reconstructed Lean audit sources, the exact named audit and full raw ownership inventory are preserved. The complete ownership receipt gives counts by module and declaration kind. Actual failed source logs, if any, remain scoped failures and are excluded from both acceptance audits.
'''
(evidence/'README.md').write_text(text)
print(str(evidence/'README.md'))
