import ThueMorseMAP.Headline
#print axioms ThueMorseBits.t
#print axioms ThueMorseBits.t_zero
#print axioms ThueMorseBits.t_double
#print axioms ThueMorseBits.t_double_add_one
#print axioms ThueMorseBits.t_one
#print axioms ThueMorseBits.t_dyadic_block
#print axioms ThueMorseBits.index_lt_two_pow
#print axioms ThueMorseBits.t_mul_two_pow
#print axioms ThueMorseBits.t_two_pow
#print axioms ThueMorseBits.t_power_sub_three
#print axioms ThueMorseBits.t_power_sub_two
#print axioms ThueMorseBits.t_twice_power_sub_four
#print axioms ThueMorseBits.t_two
#print axioms ThueMorseBits.t_three
#print axioms ThueMorseBits.t_four
#print axioms ThueMorseBits.t_five
#print axioms ThueMorseBits.t_six
#print axioms ThueMorseBits.t_seven
#print axioms ThueMorseBits.t_eight
#print axioms ThueMorseBits.t_nine
#print axioms ThueMorseBits.t_ten
#print axioms ThueMorseBits.t_eleven
#print axioms ThueMorseBits.t_twelve
#print axioms ThueMorseBits.t_thirteen
#print axioms ThueMorseBits.t_ten_pow_add_one
#print axioms ThueMorseMAP.Run
#print axioms ThueMorseMAP.Mono
#print axioms ThueMorseMAP.FirstMaximum
#print axioms ThueMorseMAP.Center
#print axioms ThueMorseMAP.xor_self
#print axioms ThueMorseMAP.xor_cancel
#print axioms ThueMorseMAP.xor_eq_iff
#print axioms ThueMorseMAP.xor_not
#print axioms ThueMorseMAP.pow_pos
#print axioms ThueMorseMAP.pow_ge_four
#print axioms ThueMorseMAP.equal_adjacent_odd
#print axioms ThueMorseMAP.complement
#print axioms ThueMorseMAP.center_three
#print axioms ThueMorseMAP.center_ge_three
#print axioms ThueMorseMAP.run_shift
#print axioms ThueMorseMAP.Block
#print axioms ThueMorseMAP.block_zero
#print axioms ThueMorseMAP.block_even
#print axioms ThueMorseMAP.block_desubstitute
#print axioms ThueMorseMAP.block_divides
#print axioms ThueMorseMAP.block_cases
#print axioms ThueMorseMAP.run_at
#print axioms ThueMorseMAP.tail_one
#print axioms ThueMorseMAP.tail_two
#print axioms ThueMorseMAP.tail_three
#print axioms ThueMorseMAP.half_tail_one
#print axioms ThueMorseMAP.half_tail_two
#print axioms ThueMorseMAP.odd_minus_witness
#print axioms ThueMorseMAP.odd_minus_upper
#print axioms ThueMorseMAP.odd_minus_earliest
#print axioms ThueMorseMAP.odd_minus_first_maximum
#print axioms ThueMorseMAP.minus_wrap_impossible
#print axioms ThueMorseMAP.even_minus_residue
#print axioms ThueMorseMAP.even_minus_necessary
#print axioms ThueMorseMAP.even_minus_witness
#print axioms ThueMorseMAP.even_minus_classification
#print axioms ThueMorseMAP.even_minus_upper
#print axioms ThueMorseMAP.even_minus_first_maximum
#print axioms ThueMorseMAP.plus_before
#print axioms ThueMorseMAP.plus_after
#print axioms ThueMorseMAP.plus_residue_options
#print axioms ThueMorseMAP.plus_final_block
#print axioms ThueMorseMAP.half_plus_one
#print axioms ThueMorseMAP.plus_not_zero
#print axioms ThueMorseMAP.plus_not_penultimate
#print axioms ThueMorseMAP.plus_necessary
#print axioms ThueMorseMAP.plus_witness
#print axioms ThueMorseMAP.plus_classification
#print axioms ThueMorseMAP.plus_upper
#print axioms ThueMorseMAP.plus_first_maximum
#print axioms ThueMorseMAP.A
#print axioms ThueMorseMAP.i
#print axioms ThueMorseMAP.Mono.truncate
#print axioms ThueMorseMAP.FirstMaximum.bindings
#print axioms ThueMorseMAP.conjecture_3_8_plus
#print axioms ThueMorseMAP.conjecture_3_8_even_minus
#print axioms ThueMorseMAP.conjecture_3_8_odd_minus
